// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import CommentPageController from "./comment_page_controller"
application.register("comment-page", CommentPageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import InsightController from "./insight_controller"
application.register("insight", InsightController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import InsightButtonController from "./insight_button_controller"
application.register("insight-button", InsightButtonController)