meta_name: "Get Goals!"
meta_title: "Be a man. Be a goal-getter"
meta_description: "Set goals. Get it. Dominate. Ape!"
meta_image: "goals-index.jpg" # should exist in `app/assets/images/`
twitter_account: "@SamFandG"
